### ISSUE TITLE
Function explination

### ISSUE THREAD

**Issue by DonEros** [AngelSecurityTeam/CC_Scrapper#3]
Hey team trust that you're well may you please, assist in defining what is required and what these functions mean, what they do, and an example of how you should fill them out?

there is no issue with the code, I just need a better understanding of what is required.

Enter Number Of Days Of Messages  = 

Example Channel or Group :
https://t.me/name
@name
tg://join?invite=code_name
https://t.me/joinchat/code_name

Channel/Group:

FILE NAME =

**Comment by AngelSecurityTeam** [comment]
messages in the groups type

4000221111111111|10|25|000
